import { GoogleGenAI } from "@google/genai";
import { BackgroundType } from "../types";

// Helper to remove data URL prefix for API
const cleanBase64 = (dataUrl: string) => {
  return dataUrl.split(',')[1];
};

export const generateIdPhoto = async (
  base64Image: string, 
  backgroundType: BackgroundType
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Prompt engineering for Gemini 2.5 Flash Image
  // We ask it to modify the background while preserving the subject
  const colorDesc = backgroundType === BackgroundType.BLUE ? "solid azure blue (#007FFF)" : "solid white";
  
  const prompt = `
    I need a professional ID photo (passport style) of the person in this image.
    1. Keep the person's face and upper body exactly as they are. Do not alter their facial features or identity.
    2. Change the background to a strictly ${colorDesc}.
    3. Ensure the lighting on the subject looks natural against the new background.
    4. The output must be high quality.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', // Assuming jpeg for simplicity, API handles png/jpeg
              data: cleanBase64(base64Image)
            }
          },
          { text: prompt }
        ]
      }
    });

    // Check for image in response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};